FROM node:20

WORKDIR /app

# Kopiuj package.json
COPY package*.json ./

# Instaluj dependencies + Angular CLI globalnie
RUN npm ci && npm install -g @angular/cli

# Kopiuj kod źródłowy
COPY . .

# Otwórz port 4200
EXPOSE 4200

# Uruchom development server
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000"]
