services:
  backend:
    image: chalbrik/planner-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_IN_DOCKER=True
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    image: chalbrik/planner-frontend:latest
    ports:
      - "4200:80"