# Generated by Django 5.1.7 on 2025-03-23 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data pracy')),
                ('hours', models.CharField(help_text='np. 8:00-16:00', max_length=50, verbose_name='Godziny pracy')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='schedule.employee', verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Godziny pracy',
                'verbose_name_plural': 'Godziny pracy',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
