# Generated by Django 5.1.7 on 2025-08-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='agreementType',
            field=models.CharField(choices=[('permanent', 'Umowa o pracę'), ('contract', 'Umowa na zlecenie')], default='permanent', max_length=20, verbose_name='Rodzaj umowy'),
        ),
    ]
