# Generated by Django 5.1.7 on 2025-08-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_add_agreement_type_to_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='agreementType',
            new_name='agreement_type',
        ),
    ]
