# Generated by Django 5.1.7 on 2025-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_edit_agreement_type_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia umowy'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia umowy'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hour_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stawka godzinowa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numer ewidencyjny'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Wymiar etatu'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stawka etatowa'),
        ),
    ]
