# Generated by Django 5.1.7 on 2025-08-10 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_employee_contract_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_vacation_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Bieżący urlop (dni)')),
                ('current_vacation_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Wykorzystano (dni)')),
                ('remaining_vacation_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Zaległy urlop (dni)')),
                ('remaining_vacation_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Zaległy urlop (godziny)')),
                ('used_vacation_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Wykorzystano (dni)')),
                ('used_vacation_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Wykorzystano (godziny)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_leaves', to='schedule.employee', verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Urlop',
                'verbose_name_plural': 'Urlopy',
            },
        ),
    ]
