# Generated by Django 5.1.7 on 2025-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_vacationleave_current_vacation_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationleave',
            name='current_vacation_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Bieżący urlop (godziny)'),
        ),
    ]
