# Generated by Django 5.1.7 on 2025-08-13 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('agreement_type', models.CharField(choices=[('permanent', 'Umowa o pracę'), ('contract', 'Umowa na zlecenie')], default='permanent', max_length=20, verbose_name='Rodzaj umowy')),
                ('identification_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numer ewidencyjny')),
                ('job', models.CharField(blank=True, max_length=20, null=True, verbose_name='Wymiar etatu')),
                ('contract_date_start', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia umowy')),
                ('contract_date_end', models.DateField(blank=True, null=True, verbose_name='Data zakończenia umowy')),
                ('job_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stawka etatowa')),
                ('hour_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stawka godzinowa')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='VacationLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_vacation_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Bieżący urlop (dni)')),
                ('current_vacation_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Bieżący urlop (godziny)')),
                ('remaining_vacation_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Zaległy urlop (dni)')),
                ('remaining_vacation_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Zaległy urlop (godziny)')),
                ('used_vacation_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Wykorzystano (dni)')),
                ('used_vacation_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Wykorzystano (godziny)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_leaves', to='employees.employee', verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Urlop',
                'verbose_name_plural': 'Urlopy',
            },
        ),
    ]
