# Generated by Django 5.1.7 on 2025-08-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_location'),
        ('locations', '0002_location_identification_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.AddField(
            model_name='employee',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='employees', to='locations.location', verbose_name='Lokacja'),
        ),
    ]
