# Generated by Django 5.1.7 on 2025-08-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_location_employee_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previousemployers',
            options={'verbose_name': 'Poprzedni pracodawca', 'verbose_name_plural': 'Poprzedni pracodawcy'},
        ),
    ]
