# Generated by Django 5.1.7 on 2025-10-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='employees.employee', verbose_name='Pracownik'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(blank=True, default='Nieznany', max_length=200, verbose_name='Nazwa szkoły'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, default='Nieznany', max_length=100, verbose_name='Typ szkoły'),
        ),
    ]
