# Generated by Django 5.1.7 on 2025-10-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_school_employee_alter_school_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='agreement_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Umowa o pracę'), ('contract', 'Umowa na zlecenie')], default='permanent', max_length=20, verbose_name='Rodzaj umowy'),
        ),
    ]
