# Generated by Django 5.1.7 on 2025-12-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_agreement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identification_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Numer ewidencyjny'),
        ),
    ]
