# Generated by Django 5.1.7 on 2025-08-17 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEmployers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pracodawca/Nazwa firmy')),
                ('employee_position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stanowisko')),
                ('work_date_start', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia pracy')),
                ('work_date_end', models.DateField(blank=True, null=True, verbose_name='Data zakończenia pracy')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_employers', to='employees.employee', verbose_name='Pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Typ szkoły')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nazwa szkoły')),
                ('gradution_year', models.DateField(blank=True, null=True, verbose_name='Rok ukończenia szkoły')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='School', to='employees.employee', verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Szkoła',
                'verbose_name_plural': 'Szkoły',
            },
        ),
    ]
