# Generated by Django 5.1.7 on 2025-08-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_previousemployers_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='gradution_year',
            new_name='graduation_year',
        ),
    ]
