# Generated by Django 5.1.7 on 2025-08-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_gradution_year_school_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(default='Nieznany', max_length=200, verbose_name='Nazwa szkoły'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(default='Nieznany', max_length=100, verbose_name='Typ szkoły'),
        ),
    ]
