# Generated by Django 5.1.7 on 2025-08-13 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Data pracy')),
                ('hours', models.CharField(help_text='np. 8:00-16:00', max_length=50, verbose_name='Godziny pracy')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='employees.employee', verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Godziny pracy',
                'verbose_name_plural': 'Godziny pracy',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
