# Generated by Django 5.1.7 on 2025-08-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_location_employee_locations'),
        ('locations', '0002_location_identification_number'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workhours',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workhours',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Lokacja'),
        ),
        migrations.AlterUniqueTogether(
            name='workhours',
            unique_together={('employee', 'location', 'date')},
        ),
    ]
