# Generated by Django 5.1.7 on 2025-08-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_workhours_unique_together_workhours_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workhours',
            unique_together=set(),
        ),
    ]
