# Generated by Django 5.1.7 on 2025-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_agreement_type'),
        ('locations', '0003_location_user'),
        ('schedule', '0003_alter_workhours_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhours',
            options={'ordering': ['date', 'employee'], 'verbose_name': 'Godziny pracy', 'verbose_name_plural': 'Godziny pracy'},
        ),
        migrations.AddIndex(
            model_name='workhours',
            index=models.Index(fields=['location', 'date'], name='workhours_loc_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workhours',
            index=models.Index(fields=['employee', 'date'], name='workhours_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workhours',
            index=models.Index(fields=['date'], name='workhours_date_idx'),
        ),
    ]
