# Generated by Django 5.1.7 on 2025-08-19 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa lokacji')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Lokacja',
                'verbose_name_plural': 'Lokacje',
                'ordering': ['name'],
            },
        ),
    ]
