# Generated by Django 5.1.7 on 2025-08-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numer lokacji'),
        ),
    ]
