# Generated by Django 5.1.7 on 2025-12-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='identification_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Numer lokacji'),
        ),
    ]
